### ISSUE TITLE
validate compatibility with Puppet 7 (and 8?)

### ISSUE THREAD

**Issue by timmooney** [Slashbunny/puppet-phpfpm#42]
I'm not familiar with the CI infrastructure so this may be an ignorant question, but are there plans to validate phpfpm module compatibility with Puppet 7 and potentially Puppet 8?

After a lot of step-wise upgrades of Forge modules, Slashbunny-phpfpm is the last module we use that doesn't claim support for Puppet 7 (or 8).  I expect it will work just fine on at least Puppet 7.  I haven't looked at what's changed with 8 so no idea there.

**Comment by Slashbunny** [comment]
I do not currently use this module, so I am relying on others to do any sort of extensive testing. The CI system was using TravisCI, but it doesn't appear to be working at the moment. I reckon I should just switch over to GitHub Actions. I will take a look at doing that. 

However, like you said, I suspect this module will most likely work fine, since it is quite simple!

**Comment by timmooney** [comment]
I upgraded our puppetserver packages to the 7.x series (7.16) and there have not been any issues with this module so far, so if it's not too difficult to add the GitHub CI, I suspect it will show that it works with later puppetserver versions and with later OS releases
(we've been using it without trouble on RedHat 8.x and 9.x too, and now with PHP 8.0 and 8.1).

Thanks for taking a look at GitHub actions, especially since you're not using it currently.

**Comment by Slashbunny** [comment]
Hi @timmooney, sorry this took forever me to get to! I completely re-did all the CI stuff in the repo using GitHub Actions. Static analysis runs on all supported versions of Puppet now (7.x and 8.x at the moment)!
