### ISSUE TITLE
phpfpm::pool does not generate file as expected

### ISSUE THREAD

**Issue by yellow1912** [Slashbunny/puppet-phpfpm#8]
Hello,

I'm very new to puppet so I'm sure this is something that I didnt do correctly but I could not figure out the issue:

I use https://puphpet.com/ to generate the code base I need to setup my dev environment with Vagrant. However, I want to use this module to easily manage the fpm pool so I installed the module and made some small changes to the Nginx.pp node to try it out:

http://www.sourcepod.com/qgajpv94-64021

Not sure what I did wrong but it seems like the phpfpm file never got created?

**Comment by Slashbunny** [comment]
I can't tell what could be going wrong based on all that code, you'd need to look at the output of `puppet agent -t' to see what may be going wrong. 

Doesn't puphpet use php-fpm if you choose nginx? As far as I know, fpm is the only supported way these days to use PHP with nginx. It's possible there could be some incompatibility between `puppet-phpfpm` and whatever puphpet is doing since I assume it's trying to do something similar.
